import ElementCard from "./components/ElementCard";
import "./App.css";

export default function App() {
  return (
    <div
      style={{
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        height: "100vh",
      }}
    >
      <div
        style={{
          padding: "75px",
          overflowX: "auto",
          display: "flex",
          alignItems: "center",
        }}
      >
        <div
          style={{
            paddingTop: "75px",
            display: "flex",
            flexDirection: "column",
            gap: 5,
          }}
        >
          <div className="topContainer">
            <div className="container-1">
              <div className="container-wrapper">
                <ElementCard
                  atomicNumber="1"
                  name="Hydrogen"
                  atomicMass="1.0080"
                  symbol="H"
                  background="#2A4165"
                />
                <ElementCard
                  atomicNumber="3"
                  name="Lithium"
                  atomicMass="7.0"
                  symbol="Li"
                  background="#244D57"
                />
                <ElementCard
                  atomicNumber="11"
                  name="Sodium"
                  atomicMass="22.9897693"
                  symbol="Na"
                  background="#244D57"
                />
                <ElementCard
                  atomicNumber="19"
                  name="Potassium"
                  atomicMass="39.0983"
                  symbol="K"
                  background="#244D57"
                />
                <ElementCard
                  atomicNumber="37"
                  name="Rubidium"
                  atomicMass="85.468"
                  symbol="Rb"
                  background="#244D57"
                />
                <ElementCard
                  atomicNumber="55"
                  name="Cesium"
                  atomicMass="132.9054520"
                  symbol="Cs"
                  background="#244D57"
                />
                <ElementCard
                  atomicNumber="87"
                  name="Francium"
                  atomicMass="223.01973"
                  symbol="Fr"
                  background="#244D57"
                />
              </div>
              <div className="container-wrapper">
                <ElementCard />
                <ElementCard
                  atomicNumber="4"
                  name="Beryllium"
                  atomicMass="9.012183"
                  symbol="Be"
                  background="#622E39"
                />
                <ElementCard
                  atomicNumber="12"
                  name="Magnesium"
                  atomicMass="24.305"
                  symbol="Mg"
                  background="#622E39"
                />
                <ElementCard
                  atomicNumber="20"
                  name="Calcium"
                  atomicMass="40.08"
                  symbol="Ca"
                  background="#622E39"
                />
                <ElementCard
                  atomicNumber="38"
                  name="Strontium"
                  atomicMass="87.62"
                  symbol="Sr"
                  background="#622E39"
                />
                <ElementCard
                  atomicNumber="56"
                  name="Barium"
                  atomicMass="137.33"
                  symbol="Ba"
                  background="#622E39"
                />
                <ElementCard
                  atomicNumber="88"
                  name="Radium"
                  atomicMass="226.02541"
                  symbol="Ra"
                  background="#622E39"
                />
              </div>
              <div className="container-wrapper">
                <ElementCard />
                <ElementCard />
                <ElementCard />
                <ElementCard
                  atomicNumber="21"
                  name="Scandium"
                  atomicMass="44.95591"
                  symbol="Sc"
                  background="#433C65"
                />
                <ElementCard
                  atomicNumber="39"
                  name="Yttrium"
                  atomicMass="88.90584"
                  symbol="Y"
                  background="#433C65"
                />
                <ElementCard />
                <ElementCard />
              </div>
            </div>
            <div className="container-2">
              <div className="container-wrapper">
                <ElementCard />
                <ElementCard />
                <ElementCard />
                <ElementCard
                  atomicNumber="22"
                  name="Titanium"
                  atomicMass="47.867"
                  symbol="Ti"
                  background="#433C65"
                />
                <ElementCard
                  atomicNumber="40"
                  name="Zirconium"
                  atomicMass="91.22"
                  symbol="Zr"
                  background="#433C65"
                />
                <ElementCard
                  atomicNumber="72"
                  name="Hafnium"
                  atomicMass="178.49"
                  symbol="Hf"
                  background="#433C65"
                />
                <ElementCard
                  atomicNumber="104"
                  name="Rutherfordium"
                  atomicMass="267.122"
                  symbol="Rf"
                  background="#433C65"
                />
              </div>
              <div className="container-wrapper">
                <ElementCard />
                <ElementCard />
                <ElementCard />
                <ElementCard
                  atomicNumber="23"
                  name="Vanadium"
                  atomicMass="50.9415"
                  symbol="V"
                  background="#433C65"
                />
                <ElementCard
                  atomicNumber="41"
                  name="Niobium"
                  atomicMass="92.90637"
                  symbol="Nb"
                  background="#433C65"
                />
                <ElementCard
                  atomicNumber="73"
                  name="Tantalum"
                  atomicMass="180.9479"
                  symbol="Ta"
                  background="#433C65"
                />
                <ElementCard
                  atomicNumber="105"
                  name="Dubnium"
                  atomicMass="268.126"
                  symbol="Db"
                  background="#433C65"
                />
              </div>
              <div className="container-wrapper">
                <ElementCard />
                <ElementCard />
                <ElementCard />
                <ElementCard
                  atomicNumber="24"
                  name="Chromium"
                  atomicMass="51.996"
                  symbol="Cr"
                  background="#433C65"
                />
                <ElementCard
                  atomicNumber="42"
                  name="Molybdenum"
                  atomicMass="95.95"
                  symbol="Mo"
                  background="#433C65"
                />
                <ElementCard
                  atomicNumber="74"
                  name="Tungsten"
                  atomicMass="183.84"
                  symbol="W"
                  background="#433C65"
                />
                <ElementCard
                  atomicNumber="106"
                  name="Seaborgium"
                  atomicMass="269.128"
                  symbol="Sg"
                  background="#433C65"
                />
              </div>
              <div className="container-wrapper">
                <ElementCard />
                <ElementCard />
                <ElementCard />
                <ElementCard
                  atomicNumber="25"
                  name="Manganese"
                  atomicMass="54.93804"
                  symbol="Mn"
                  background="#433C65"
                />
                <ElementCard
                  atomicNumber="43"
                  name="Technetium"
                  atomicMass="96.90636"
                  symbol="Tc"
                  background="#433C65"
                />
                <ElementCard
                  atomicNumber="75"
                  name="Rhenium"
                  atomicMass="186.207"
                  symbol="Re"
                  background="#433C65"
                />
                <ElementCard
                  atomicNumber="107"
                  name="Bohrium"
                  atomicMass="270.133"
                  symbol="Bh"
                  background="#433C65"
                />
              </div>
              <div className="container-wrapper">
                <ElementCard />
                <ElementCard />
                <ElementCard />
                <ElementCard
                  atomicNumber="26"
                  name="Iron"
                  atomicMass="55.84"
                  symbol="Fe"
                  background="#433C65"
                />
                <ElementCard
                  atomicNumber="44"
                  name="Ruthenium"
                  atomicMass="101.1"
                  symbol="Ru"
                  background="#433C65"
                />
                <ElementCard
                  atomicNumber="76"
                  name="Osmium"
                  atomicMass="190.2"
                  symbol="Os"
                  background="#433C65"
                />
                <ElementCard
                  atomicNumber="108"
                  name="Hassium"
                  atomicMass="269.1336"
                  symbol="Hs"
                  background="#433C65"
                />
              </div>
              <div className="container-wrapper">
                <ElementCard />
                <ElementCard />
                <ElementCard />
                <ElementCard
                  atomicNumber="27"
                  name="Cobalt"
                  atomicMass="58.93319"
                  symbol="Co"
                  background="#433C65"
                />
                <ElementCard
                  atomicNumber="45"
                  name="Rhodium"
                  atomicMass="102.9055"
                  symbol="Rh"
                  background="#433C65"
                />
                <ElementCard
                  atomicNumber="77"
                  name="Iridium"
                  atomicMass="192.22"
                  symbol="Ir"
                  background="#433C65"
                />
                <ElementCard
                  atomicNumber="109"
                  name="Meitnerium"
                  atomicMass="277.154"
                  symbol="Mt"
                  background="#46474C"
                />
              </div>
              <div className="container-wrapper">
                <ElementCard />
                <ElementCard />
                <ElementCard />
                <ElementCard
                  atomicNumber="28"
                  name="Nickel"
                  atomicMass="58.693"
                  symbol="Ni"
                  background="#433C65"
                />
                <ElementCard
                  atomicNumber="46"
                  name="Palladium"
                  atomicMass="106.42"
                  symbol="Pd"
                  background="#433C65"
                />
                <ElementCard
                  atomicNumber="78"
                  name="Platinum"
                  atomicMass="195.08"
                  symbol="Pt"
                  background="#433C65"
                />
                <ElementCard
                  atomicNumber="110"
                  name="Darmstadtium"
                  atomicMass="282.166"
                  symbol="Ds"
                  background="#46474C"
                />
              </div>
              <div className="container-wrapper">
                <ElementCard />
                <ElementCard />
                <ElementCard />
                <ElementCard
                  atomicNumber="29"
                  name="Copper"
                  atomicMass="63.55"
                  symbol="Cu"
                  background="#433C65"
                />
                <ElementCard
                  atomicNumber="47"
                  name="Silver"
                  atomicMass="107.868"
                  symbol="Ag"
                  background="#433C65"
                />
                <ElementCard
                  atomicNumber="79"
                  name="Gold"
                  atomicMass="196.96657"
                  symbol="Au"
                  background="#433C65"
                />
                <ElementCard
                  atomicNumber="111"
                  name="Roentgenium"
                  atomicMass="282.169"
                  symbol="Rg"
                  background="#46474C"
                />
              </div>
              <div className="container-wrapper">
                <ElementCard />
                <ElementCard />
                <ElementCard />
                <ElementCard
                  atomicNumber="30"
                  name="Zinc"
                  atomicMass="65.4"
                  symbol="Zn"
                  background="#433C65"
                />
                <ElementCard
                  atomicNumber="48"
                  name="Cadmium"
                  atomicMass="112.41"
                  symbol="Cd"
                  background="#433C65"
                />
                <ElementCard
                  atomicNumber="80"
                  name="Mercury"
                  atomicMass="200.59"
                  symbol="Hg"
                  background="#433C65"
                />
                <ElementCard
                  atomicNumber="112"
                  name="Copernicium"
                  atomicMass="286.179"
                  symbol="Cn"
                  background="#46474C"
                />
              </div>
              <div className="container-wrapper">
                <ElementCard />
                <ElementCard
                  atomicNumber="5"
                  name="Boron"
                  atomicMass="10.81"
                  symbol="B"
                  background="#523E1B"
                />
                <ElementCard
                  atomicNumber="13"
                  name="Aluminum"
                  atomicMass="26.981538"
                  symbol="Al"
                  background="#2F4D47"
                />
                <ElementCard
                  atomicNumber="31"
                  name="Gallium"
                  atomicMass="69.723"
                  symbol="Ga"
                  background="#2F4D47"
                />
                <ElementCard
                  atomicNumber="49"
                  name="Indium"
                  atomicMass="114.818"
                  symbol="In"
                  background="#2F4D47"
                />
                <ElementCard
                  atomicNumber="81"
                  name="Thallium"
                  atomicMass="204.383"
                  symbol="Tl"
                  background="#2F4D47"
                />
                <ElementCard
                  atomicNumber="113"
                  name="Nihonium"
                  atomicMass="286.182"
                  symbol="Nh"
                  background="#46474C"
                />
              </div>
              <div className="container-wrapper">
                <ElementCard />
                <ElementCard
                  atomicNumber="6"
                  name="Carbon"
                  atomicMass="12.011"
                  symbol="C"
                  background="#2A4165"
                />
                <ElementCard
                  atomicNumber="14"
                  name="Silicon"
                  atomicMass="28.085"
                  symbol="Si"
                  background="#523E1B"
                />
                <ElementCard
                  atomicNumber="32"
                  name="Germanium"
                  atomicMass="72.63"
                  symbol="Ge"
                  background="#523E1B"
                />
                <ElementCard
                  atomicNumber="50"
                  name="Tin"
                  atomicMass="118.71"
                  symbol="Sn"
                  background="#2F4D47"
                />
                <ElementCard
                  atomicNumber="82"
                  name="Lead"
                  atomicMass="207"
                  symbol="Pb"
                  background="#2F4D47"
                />
                <ElementCard
                  atomicNumber="114"
                  name="Flerovium"
                  atomicMass="290.192"
                  symbol="Fl"
                  background="#46474C"
                />
              </div>
              <div className="container-wrapper">
                <ElementCard />
                <ElementCard
                  atomicNumber="7"
                  name="Nitrogen"
                  atomicMass="14.007"
                  symbol="N"
                  background="#2A4165"
                />
                <ElementCard
                  atomicNumber="15"
                  name="Phosphorus"
                  atomicMass="30.97376200"
                  symbol="P"
                  background="#2A4165"
                />
                <ElementCard
                  atomicNumber="33"
                  name="Arsenic"
                  atomicMass="74.92159"
                  symbol="As"
                  background="#523E1B"
                />
                <ElementCard
                  atomicNumber="51"
                  name="Antimony"
                  atomicMass="121.760"
                  symbol="Sb"
                  background="#523E1B"
                />
                <ElementCard
                  atomicNumber="83"
                  name="Bismuth"
                  atomicMass="208.98040"
                  symbol="Bi"
                  background="#2F4D47"
                />
                <ElementCard
                  atomicNumber="115"
                  name="Moscovium"
                  atomicMass="290.196"
                  symbol="Mc"
                  background="#46474C"
                />
              </div>
              <div className="container-wrapper">
                <ElementCard />
                <ElementCard
                  atomicNumber="8"
                  name="Oxygen"
                  atomicMass="15.999"
                  symbol="O"
                  background="#2A4165"
                />
                <ElementCard
                  atomicNumber="16"
                  name="Sulfur"
                  atomicMass="32.07"
                  symbol="S"
                  background="#2A4165"
                />
                <ElementCard
                  atomicNumber="34"
                  name="Selenium"
                  atomicMass="78.97"
                  symbol="Se"
                  background="#2A4165"
                />
                <ElementCard
                  atomicNumber="52"
                  name="Tellurium"
                  atomicMass="127.6"
                  symbol="Te"
                  background="#523E1B"
                />
                <ElementCard
                  atomicNumber="84"
                  name="Polonium"
                  atomicMass="208.98243"
                  symbol="Po"
                  background="#2F4D47"
                />
                <ElementCard
                  atomicNumber="116"
                  name="Livermorium"
                  atomicMass="293.205"
                  symbol="Lv"
                  background="#46474C"
                />
              </div>
              <div className="container-wrapper">
                <ElementCard />
                <ElementCard
                  atomicNumber="9"
                  name="Fluorine"
                  atomicMass="18.99840316"
                  symbol="F"
                  background="#2A4165"
                />
                <ElementCard
                  atomicNumber="17"
                  name="Chlorine"
                  atomicMass="35.45"
                  symbol="Cl"
                  background="#2A4165"
                />
                <ElementCard
                  atomicNumber="35"
                  name="Bromine"
                  atomicMass="79.90"
                  symbol="Br"
                  background="#2A4165"
                />
                <ElementCard
                  atomicNumber="53"
                  name="Iodine"
                  atomicMass="126.9045"
                  symbol="I"
                  background="#2A4165"
                />
                <ElementCard
                  atomicNumber="85"
                  name="Astatine"
                  atomicMass="209.98715"
                  symbol="At"
                  background="#2F4D47"
                />
                <ElementCard
                  atomicNumber="117"
                  name="Tennessine"
                  atomicMass="294.211"
                  symbol="Ts"
                  background="#46474C"
                />
              </div>
              <div className="container-wrapper">
                <ElementCard
                  atomicNumber="2"
                  name="Helium"
                  atomicMass="4.00260"
                  symbol="He"
                  background="#623842"
                />
                <ElementCard
                  atomicNumber="10"
                  name="Neon"
                  atomicMass="20.180"
                  symbol="Ne"
                  background="#623842"
                />
                <ElementCard
                  atomicNumber="18"
                  name="Argon"
                  atomicMass="39.9"
                  symbol="Ar"
                  background="#623842"
                />
                <ElementCard
                  atomicNumber="36"
                  name="Krypton"
                  atomicMass="83.80"
                  symbol="Kr"
                  background="#623842"
                />
                <ElementCard
                  atomicNumber="54"
                  name="Xenon"
                  atomicMass="131.29"
                  symbol="Xe"
                  background="#623842"
                />
                <ElementCard
                  atomicNumber="86"
                  name="Radon"
                  atomicMass="222.01758"
                  symbol="Rn"
                  background="#623842"
                />
                <ElementCard
                  atomicNumber="118"
                  name="Oganesson"
                  atomicMass="295.216"
                  symbol="Og"
                  background="#46474C"
                />
              </div>
            </div>
          </div>
          <div className="bottomContainer">
            <div className="bottom-container-wrapper">
              <ElementCard />
              <ElementCard />
              <ElementCard />
              <ElementCard
                atomicNumber="57"
                name="Lanthanum"
                atomicMass="138.9055"
                symbol="La"
                background="#004A77"
              />
              <ElementCard
                atomicNumber="58"
                name="Cerium"
                atomicMass="140.116"
                symbol="Ce"
                background="#004A77"
              />
              <ElementCard
                atomicNumber="59"
                name="Praseodymium"
                atomicMass="140.90766"
                symbol="Pr"
                background="#004A77"
              />
              <ElementCard
                atomicNumber="60"
                name="Neodymium"
                atomicMass="144.24"
                symbol="Nd"
                background="#004A77"
              />
              <ElementCard
                atomicNumber="61"
                name="Promethium"
                atomicMass="144.91276"
                symbol="Pm"
                background="#004A77"
              />
              <ElementCard
                atomicNumber="62"
                name="Samarium"
                atomicMass="150.4"
                symbol="Sm"
                background="#004A77"
              />
              <ElementCard
                atomicNumber="63"
                name="Europium"
                atomicMass="151.964"
                symbol="Eu"
                background="#004A77"
              />
              <ElementCard
                atomicNumber="64"
                name="Gadolinium"
                atomicMass="157.2"
                symbol="Gd"
                background="#004A77"
              />
              <ElementCard
                atomicNumber="65"
                name="Terbium"
                atomicMass="158.92535"
                symbol="Tb"
                background="#004A77"
              />
              <ElementCard
                atomicNumber="66"
                name="Dysprosium"
                atomicMass="162.500"
                symbol="Dy"
                background="#004A77"
              />
              <ElementCard
                atomicNumber="67"
                name="Holmium"
                atomicMass="164.93033"
                symbol="Ho"
                background="#004A77"
              />
              <ElementCard
                atomicNumber="68"
                name="Erbium"
                atomicMass="167.26"
                symbol="Er"
                background="#004A77"
              />
              <ElementCard
                atomicNumber="69"
                name="Thulium"
                atomicMass="168.93422"
                symbol="Tm"
                background="#004A77"
              />
              <ElementCard
                atomicNumber="70"
                name="Ytterbium"
                atomicMass="173.05"
                symbol="Yb"
                background="#004A77"
              />
              <ElementCard
                atomicNumber="71"
                name="Lutetium"
                atomicMass="174.9668"
                symbol="Lu"
                background="#004A77"
              />
            </div>
            <div className="bottom-container-wrapper">
              <ElementCard />
              <ElementCard />
              <ElementCard />
              <ElementCard
                atomicNumber="89"
                name="Actinium"
                atomicMass="227.02775"
                symbol="Ac"
                background="#613B28"
              />
              <ElementCard
                atomicNumber="90"
                name="Thorium"
                atomicMass="232.038"
                symbol="Th"
                background="#613B28"
              />
              <ElementCard
                atomicNumber="91"
                name="Protactinium"
                atomicMass="231.03588"
                symbol="Pa"
                background="#613B28"
              />
              <ElementCard
                atomicNumber="92"
                name="Uranium"
                atomicMass="238.0289"
                symbol="U"
                background="#613B28"
              />
              <ElementCard
                atomicNumber="93"
                name="Neptunium"
                atomicMass="237.048172"
                symbol="Np"
                background="#613B28"
              />
              <ElementCard
                atomicNumber="94"
                name="Plutonium"
                atomicMass="244.06420"
                symbol="Pu"
                background="#613B28"
              />
              <ElementCard
                atomicNumber="95"
                name="Americium"
                atomicMass="243.061380"
                symbol="Am"
                background="#613B28"
              />
              <ElementCard
                atomicNumber="96"
                name="Curium"
                atomicMass="247.07035"
                symbol="Cm"
                background="#613B28"
              />
              <ElementCard
                atomicNumber="97"
                name="Berkelium"
                atomicMass="247.07031"
                symbol="Bk"
                background="#613B28"
              />
              <ElementCard
                atomicNumber="98"
                name="Californium"
                atomicMass="251.07959"
                symbol="Cf"
                background="#613B28"
              />
              <ElementCard
                atomicNumber="99"
                name="Einsteinium"
                atomicMass="252.0830"
                symbol="Es"
                background="#613B28"
              />
              <ElementCard
                atomicNumber="100"
                name="Fermium"
                atomicMass="257.09511"
                symbol="Fm"
                background="#613B28"
              />
              <ElementCard
                atomicNumber="101"
                name="Mendelevium"
                atomicMass="258.09843"
                symbol="Md"
                background="#613B28"
              />
              <ElementCard
                atomicNumber="102"
                name="Nobelium"
                atomicMass="259.10100"
                symbol="No"
                background="#613B28"
              />
              <ElementCard
                atomicNumber="103"
                name="Lawrencium"
                atomicMass="266.120"
                symbol="Lr"
                background="#613B28"
              />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
